### ISSUE TITLE
Bastion in data.js

### ISSUE THREAD

**Issue by elliotCamblor** [andrewkarch/OverwatchCounters#3]
It looks like bastion has tracer as both a strength and a weakness, not sure if this is intentional or not. This looks great by the way!

**Comment by FenrirUnbound** [comment]
> It looks like bastion has tracer as both a strength and a weakness

That might be because the source of the heroes data.

The [counters entry for Tracer](http://overwatch.gamepedia.com/Tracer):
![screen shot 2016-11-07 at 9 18 00 pm](https://cloud.githubusercontent.com/assets/721148/20087710/dd49865e-a52f-11e6-9b57-1593ac21efe4.png)

The [counters entry for Bastion](http://overwatch.gamepedia.com/Bastion):

![screen shot 2016-11-07 at 9 18 27 pm](https://cloud.githubusercontent.com/assets/721148/20087700/cedf0aa8-a52f-11e6-9596-d9c09f4efafb.png)

**Comment by andrewkarch** [comment]
I am in the process of a major rewrite of the engine that determines counters.

The new engine uses more data points (3-4 times more), calculates a score for every hero, instead of just the counters and weaknesses, and it will factor in hard and soft counters.

The data has been created, I'm checking the new algorithm's math, and I just need to copy some old data in to the new.  Expect it today or tomorrow.
